// <auto-generated />
using MagicWise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicWise.Data.Migrations
{
    [DbContext(typeof(MagicWiseDbContext))]
    [Migration("20260919202515_FixDestinationTagSlugs")]
    partial class FixDestinationTagSlugs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("MagicWise.Data.Entities.DestinationTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("DestinationId", "TagId")
                        .IsUnique();

                    b.ToTable("DestinationTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationId = "waltdisneyworldresort",
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            DestinationId = "waltdisneyworldresort",
                            TagId = 11
                        },
                        new
                        {
                            Id = 3,
                            DestinationId = "waltdisneyworldresort",
                            TagId = 16
                        },
                        new
                        {
                            Id = 4,
                            DestinationId = "disneylandresort",
                            TagId = 1
                        },
                        new
                        {
                            Id = 5,
                            DestinationId = "disneylandresort",
                            TagId = 11
                        },
                        new
                        {
                            Id = 6,
                            DestinationId = "disneylandresort",
                            TagId = 16
                        },
                        new
                        {
                            Id = 7,
                            DestinationId = "dlp",
                            TagId = 1
                        },
                        new
                        {
                            Id = 8,
                            DestinationId = "dlp",
                            TagId = 12
                        },
                        new
                        {
                            Id = 9,
                            DestinationId = "dlp",
                            TagId = 18
                        },
                        new
                        {
                            Id = 10,
                            DestinationId = "tdr",
                            TagId = 1
                        },
                        new
                        {
                            Id = 11,
                            DestinationId = "tdr",
                            TagId = 13
                        },
                        new
                        {
                            Id = 12,
                            DestinationId = "tdr",
                            TagId = 19
                        },
                        new
                        {
                            Id = 13,
                            DestinationId = "hongkongdisneylandpark",
                            TagId = 1
                        },
                        new
                        {
                            Id = 14,
                            DestinationId = "hongkongdisneylandpark",
                            TagId = 13
                        },
                        new
                        {
                            Id = 15,
                            DestinationId = "hongkongdisneylandpark",
                            TagId = 30
                        },
                        new
                        {
                            Id = 16,
                            DestinationId = "shanghaidisneyresort",
                            TagId = 1
                        },
                        new
                        {
                            Id = 17,
                            DestinationId = "shanghaidisneyresort",
                            TagId = 13
                        },
                        new
                        {
                            Id = 18,
                            DestinationId = "shanghaidisneyresort",
                            TagId = 20
                        },
                        new
                        {
                            Id = 19,
                            DestinationId = "universalresort_orlando",
                            TagId = 2
                        },
                        new
                        {
                            Id = 20,
                            DestinationId = "universalresort_orlando",
                            TagId = 11
                        },
                        new
                        {
                            Id = 21,
                            DestinationId = "universalresort_orlando",
                            TagId = 16
                        },
                        new
                        {
                            Id = 22,
                            DestinationId = "universalresort_hollywood",
                            TagId = 2
                        },
                        new
                        {
                            Id = 23,
                            DestinationId = "universalresort_hollywood",
                            TagId = 11
                        },
                        new
                        {
                            Id = 24,
                            DestinationId = "universalresort_hollywood",
                            TagId = 16
                        },
                        new
                        {
                            Id = 25,
                            DestinationId = "universalstudiosjapan",
                            TagId = 2
                        },
                        new
                        {
                            Id = 26,
                            DestinationId = "universalstudiosjapan",
                            TagId = 13
                        },
                        new
                        {
                            Id = 27,
                            DestinationId = "universalstudiosjapan",
                            TagId = 19
                        },
                        new
                        {
                            Id = 28,
                            DestinationId = "universalsingapore",
                            TagId = 2
                        },
                        new
                        {
                            Id = 29,
                            DestinationId = "universalsingapore",
                            TagId = 13
                        },
                        new
                        {
                            Id = 30,
                            DestinationId = "sixflags_destination_SFMM",
                            TagId = 3
                        },
                        new
                        {
                            Id = 31,
                            DestinationId = "sixflags_destination_SFMM",
                            TagId = 11
                        },
                        new
                        {
                            Id = 32,
                            DestinationId = "sixflags_destination_SFMM",
                            TagId = 16
                        },
                        new
                        {
                            Id = 33,
                            DestinationId = "sixflags_destination_GADV",
                            TagId = 3
                        },
                        new
                        {
                            Id = 34,
                            DestinationId = "sixflags_destination_GADV",
                            TagId = 11
                        },
                        new
                        {
                            Id = 35,
                            DestinationId = "sixflags_destination_GADV",
                            TagId = 16
                        },
                        new
                        {
                            Id = 36,
                            DestinationId = "sixflags_destination_SFOG",
                            TagId = 3
                        },
                        new
                        {
                            Id = 37,
                            DestinationId = "sixflags_destination_SFOG",
                            TagId = 11
                        },
                        new
                        {
                            Id = 38,
                            DestinationId = "sixflags_destination_SFOG",
                            TagId = 16
                        },
                        new
                        {
                            Id = 39,
                            DestinationId = "sixflags_destination_SFOT",
                            TagId = 3
                        },
                        new
                        {
                            Id = 40,
                            DestinationId = "sixflags_destination_SFOT",
                            TagId = 11
                        },
                        new
                        {
                            Id = 41,
                            DestinationId = "sixflags_destination_SFOT",
                            TagId = 16
                        },
                        new
                        {
                            Id = 42,
                            DestinationId = "sixflags_destination_SFGR",
                            TagId = 3
                        },
                        new
                        {
                            Id = 43,
                            DestinationId = "sixflags_destination_SFGR",
                            TagId = 11
                        },
                        new
                        {
                            Id = 44,
                            DestinationId = "sixflags_destination_SFGR",
                            TagId = 16
                        },
                        new
                        {
                            Id = 45,
                            DestinationId = "seaworldorlandoresort",
                            TagId = 4
                        },
                        new
                        {
                            Id = 46,
                            DestinationId = "seaworldorlandoresort",
                            TagId = 11
                        },
                        new
                        {
                            Id = 47,
                            DestinationId = "seaworldorlandoresort",
                            TagId = 16
                        },
                        new
                        {
                            Id = 48,
                            DestinationId = "seaworldsandiego",
                            TagId = 4
                        },
                        new
                        {
                            Id = 49,
                            DestinationId = "seaworldsandiego",
                            TagId = 11
                        },
                        new
                        {
                            Id = 50,
                            DestinationId = "seaworldsandiego",
                            TagId = 16
                        },
                        new
                        {
                            Id = 51,
                            DestinationId = "seaworldsanantonio",
                            TagId = 4
                        },
                        new
                        {
                            Id = 52,
                            DestinationId = "seaworldsanantonio",
                            TagId = 11
                        },
                        new
                        {
                            Id = 53,
                            DestinationId = "seaworldsanantonio",
                            TagId = 16
                        },
                        new
                        {
                            Id = 54,
                            DestinationId = "buschgardenstampa",
                            TagId = 4
                        },
                        new
                        {
                            Id = 55,
                            DestinationId = "buschgardenstampa",
                            TagId = 11
                        },
                        new
                        {
                            Id = 56,
                            DestinationId = "buschgardenstampa",
                            TagId = 16
                        },
                        new
                        {
                            Id = 57,
                            DestinationId = "buschgardenswillamsburg",
                            TagId = 4
                        },
                        new
                        {
                            Id = 58,
                            DestinationId = "buschgardenswillamsburg",
                            TagId = 11
                        },
                        new
                        {
                            Id = 59,
                            DestinationId = "buschgardenswillamsburg",
                            TagId = 16
                        },
                        new
                        {
                            Id = 60,
                            DestinationId = "legolandcaliforniaresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 61,
                            DestinationId = "legolandcaliforniaresort",
                            TagId = 11
                        },
                        new
                        {
                            Id = 62,
                            DestinationId = "legolandcaliforniaresort",
                            TagId = 16
                        },
                        new
                        {
                            Id = 63,
                            DestinationId = "legolandorlandoresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 64,
                            DestinationId = "legolandorlandoresort",
                            TagId = 11
                        },
                        new
                        {
                            Id = 65,
                            DestinationId = "legolandorlandoresort",
                            TagId = 16
                        },
                        new
                        {
                            Id = 66,
                            DestinationId = "legolandwindsorresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 67,
                            DestinationId = "legolandwindsorresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 68,
                            DestinationId = "legolandwindsorresort",
                            TagId = 17
                        },
                        new
                        {
                            Id = 69,
                            DestinationId = "legolanddeutschlandresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 70,
                            DestinationId = "legolanddeutschlandresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 71,
                            DestinationId = "legolanddeutschlandresort",
                            TagId = 25
                        },
                        new
                        {
                            Id = 72,
                            DestinationId = "altontowersresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 73,
                            DestinationId = "altontowersresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 74,
                            DestinationId = "altontowersresort",
                            TagId = 17
                        },
                        new
                        {
                            Id = 75,
                            DestinationId = "thorpeparkresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 76,
                            DestinationId = "thorpeparkresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 77,
                            DestinationId = "thorpeparkresort",
                            TagId = 17
                        },
                        new
                        {
                            Id = 78,
                            DestinationId = "chessingtonworldofadventuresresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 79,
                            DestinationId = "chessingtonworldofadventuresresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 80,
                            DestinationId = "chessingtonworldofadventuresresort",
                            TagId = 17
                        },
                        new
                        {
                            Id = 81,
                            DestinationId = "gardalandresort",
                            TagId = 5
                        },
                        new
                        {
                            Id = 82,
                            DestinationId = "gardalandresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 83,
                            DestinationId = "eftelingresort",
                            TagId = 9
                        },
                        new
                        {
                            Id = 84,
                            DestinationId = "eftelingresort",
                            TagId = 12
                        },
                        new
                        {
                            Id = 85,
                            DestinationId = "eftelingresort",
                            TagId = 24
                        },
                        new
                        {
                            Id = 86,
                            DestinationId = "europapark",
                            TagId = 10
                        },
                        new
                        {
                            Id = 87,
                            DestinationId = "europapark",
                            TagId = 12
                        },
                        new
                        {
                            Id = 88,
                            DestinationId = "europapark",
                            TagId = 25
                        },
                        new
                        {
                            Id = 89,
                            DestinationId = "phantasialanddest",
                            TagId = 12
                        },
                        new
                        {
                            Id = 90,
                            DestinationId = "phantasialanddest",
                            TagId = 25
                        },
                        new
                        {
                            Id = 91,
                            DestinationId = "tivoligardens",
                            TagId = 12
                        },
                        new
                        {
                            Id = 92,
                            DestinationId = "tivoligardens",
                            TagId = 28
                        },
                        new
                        {
                            Id = 93,
                            DestinationId = "liseberg",
                            TagId = 12
                        },
                        new
                        {
                            Id = 94,
                            DestinationId = "liseberg",
                            TagId = 29
                        },
                        new
                        {
                            Id = 95,
                            DestinationId = "portaventuraworld",
                            TagId = 8
                        },
                        new
                        {
                            Id = 96,
                            DestinationId = "portaventuraworld",
                            TagId = 12
                        },
                        new
                        {
                            Id = 97,
                            DestinationId = "portaventuraworld",
                            TagId = 26
                        },
                        new
                        {
                            Id = 98,
                            DestinationId = "plopsalanddeutschland",
                            TagId = 8
                        },
                        new
                        {
                            Id = 99,
                            DestinationId = "plopsalanddeutschland",
                            TagId = 12
                        },
                        new
                        {
                            Id = 100,
                            DestinationId = "plopsalanddeutschland",
                            TagId = 27
                        },
                        new
                        {
                            Id = 101,
                            DestinationId = "plopsaland-de-panne",
                            TagId = 8
                        },
                        new
                        {
                            Id = 102,
                            DestinationId = "plopsaland-de-panne",
                            TagId = 12
                        },
                        new
                        {
                            Id = 103,
                            DestinationId = "plopsaland-de-panne",
                            TagId = 27
                        },
                        new
                        {
                            Id = 104,
                            DestinationId = "imgworldsofadventure",
                            TagId = 14
                        },
                        new
                        {
                            Id = 105,
                            DestinationId = "imgworldsofadventure",
                            TagId = 23
                        },
                        new
                        {
                            Id = 106,
                            DestinationId = "ferrariworldabudhabi",
                            TagId = 14
                        },
                        new
                        {
                            Id = 107,
                            DestinationId = "ferrariworldabudhabi",
                            TagId = 23
                        },
                        new
                        {
                            Id = 108,
                            DestinationId = "vrtp_mw_te2_destination",
                            TagId = 14
                        },
                        new
                        {
                            Id = 109,
                            DestinationId = "vrtp_mw_te2_destination",
                            TagId = 23
                        });
                });

            modelBuilder.Entity("MagicWise.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Disney"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Universal"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Six Flags"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "SeaWorld Parks & Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Merlin Entertainments"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Cedar Fair / Paramount"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Herschend Family Entertainment"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Parques Reunidos"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Efteling"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Europa-Park"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Asia-Pacific"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Middle East"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "France"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Name = "China"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Name = "Hong Kong"
                        });
                });

            modelBuilder.Entity("MagicWise.Data.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TagCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsVisible = true,
                            Name = "Company"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsVisible = true,
                            Name = "Region"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsVisible = true,
                            Name = "Country"
                        });
                });

            modelBuilder.Entity("MagicWise.Data.Entities.DestinationTag", b =>
                {
                    b.HasOne("MagicWise.Data.Entities.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MagicWise.Data.Entities.Tag", b =>
                {
                    b.HasOne("MagicWise.Data.Entities.TagCategory", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MagicWise.Data.Entities.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("MagicWise.Data.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
